FROM node:24-bookworm-slim AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN groupadd --system --gid 1001 nodejs && \
    useradd --system --uid 1001 --gid nodejs --create-home nextjs

COPY --chown=nextjs:nodejs .next/standalone ./
COPY --chown=nextjs:nodejs .next/static     ./.next/static
COPY --chown=nextjs:nodejs public           ./public
COPY --chown=nextjs:nodejs data             ./data

USER nextjs

EXPOSE 3140
ENV PORT=3140
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
